<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCL6Hhm\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCL6Hhm/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRCL6Hhm.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerRCL6Hhm\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerRCL6Hhm\appAppKernelProdContainer([
    'container.build_hash' => 'RCL6Hhm',
    'container.build_id' => 'ece10e8d',
    'container.build_time' => 1698342095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRCL6Hhm');
