<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.mailchimp.mailchimppro.customer_sync' shared service.

return $this->services['console.command.public_alias.mailchimp.mailchimppro.customer_sync'] = new \PrestaChamps\MailchimpPro\Console\Commands\CustomersSyncCommand();
